[package]
name = "nkosi-engines"
version = "0.1.0"
edition = "2024"

[dependencies]
nkosi-common = { path = "../nkosi-common" }
nkosi-db = { path = "../nkosi-db" }
sha2.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
lru.workspace = true
regex = "1"
uuid.workspace = true
chrono.workspace = true

[features]
default = []
real-yara = ["yara"]
advanced-static = ["goblin"]

[dependencies.yara]
version = "0.32"
optional = true

[dependencies.goblin]
version = "0.8"
optional = true

[dev-dependencies]
tempfile = "3"
