[package]
name = "nkosi-integration-tests"
version = "0.1.0"
edition = "2024"

[dependencies]
nkosi-common = { path = "../nkosi-common" }
nkosi-db = { path = "../nkosi-db" }
nkosi-engines = { path = "../nkosi-engines" }
nkosi-risk = { path = "../nkosi-risk" }
nkosi-response = { path = "../nkosi-response" }
nkosi-scanner = { path = "../nkosi-scanner" }
nkosi-ti = { path = "../nkosi-ti" }
nkosi-monitors = { path = "../nkosi-monitors" }
tokio.workspace = true
tempfile.workspace = true
uuid.workspace = true
chrono.workspace = true
serde_json.workspace = true
