[package]
name = "nkosi-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
nkosi-common = { path = "../nkosi-common" }
nkosi-db = { path = "../nkosi-db" }
nkosi-engines = { path = "../nkosi-engines" }
nkosi-risk = { path = "../nkosi-risk" }
nkosi-response = { path = "../nkosi-response" }
nkosi-ti = { path = "../nkosi-ti" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
anyhow.workspace = true
ratatui = "0.29"
crossterm = "0.28"
chrono.workspace = true
walkdir = "2"
